### PR TITLE
fixed crash, removed SDL_WINDOW_OPENGL flag

### PR DESCRIPTION
**Pull request by Gwitr**
also added a .gitignore and turned some defines into constexpr values

### CODE REVIEW

**Comment by Gwitr** [comment]
git is incredibly complicated, I'm still not sure if I'm doing this correctly or if I overcomplicated everything

**Comment by Gwitr** [comment]
so uh should i close this?

**Comment by annasajkh** [comment]
im sorry im taking too long i didn't notice it lol

**Comment by Gwitr** [comment]
Ah np

**Pull request merged**
